config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "usuarios#new"

  get 'usuarios/index', to: 'usuarios#index'
  get 'usuarios/new', to: 'usuarios#new', as: :new_usuario
  post "usuarios", to: "usuarios#create"
  get 'usuarios/:id', to: "usuarios#show"
  get 'usuarios/:id/edit', to: "usuarios#edit", as: :edit_usuario
  patch "usuarios/:id", to: "usuarios#update", as: :usuario
  delete "usuarios/:id", to: "usuarios#delete"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord

  validates :tipo, presence: true, length: {minimum: 1, maximum: 1}
  validates :nombre, presence: true
  validates :apellidos, presence: true
  validates :pais, presence: true
  validates :email, presence: true, length: {minimum: 4}
  validates :contraseña, presence: true, length: {minimum: 8}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

  before_action :authenticate_user!
  before_action :find_usuario, only: [:show, :edit, :update, :delete]

  def index
    @usuario = Usuario.all
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.create(strong_params_usuarios)
    if @usuario.save
      redirect_to usuarios_index_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @usuario.update(strong_params_usuarios)
      redirect_to usuarios_index_path
    else
      render 'edit'
    end
  end

  def delete
    @usuario.destroy
    redirect_to usuarios_index_path
  end

  private

  def find_usuario
    @usuario = Usuario.find(params[:id])
  end

  def strong_params_usuarios
    params.require(:usuario).permit(:tipo, :nombre, :apellidos, :pais, :email, :contraseña)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejercicio1Daw2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <% if notice %>
      <p class="notice alert-primary"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render "parciales/nav" %>
    <%= yield %>
  </body>
</html>

app/views/parciales/_nav.html.erb
<header class="offset-md-1 col-md-10 col-xs-12">

  <div class="d-flex flex-wrap align-items-center">
    <a class="mx-3" href="#">
      <h1 id="Titulo" class="text-dark">
        DAW2
      </h1>
    </a>
  </div>

  <nav class="navbar navbar-expand-lg navbar-light bg-light mt-2">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Usuarios", usuarios_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Añadir usuario", new_usuario_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-item">
          <span class="nav-item">Usuario: <%= current_user.email %></span>
        </li>
        <% end %>
      </ul>

    </div>
  </nav>
</header>

app/views/usuarios/_form.html.erb
<%= form_with(model: @usuario, url: usuarios_path, html: { method: :post} ,local: true) do |form| %>
  <% if @usuario.errors.any? %>
    <div class="alert-danger">
        <span>
          Se han escontrado
          <%= pluralize(@usuario.errors.count, "error") %>:
        </span>
      <ul>
        <% @usuario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">

    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <%= form.label :tipo %>
        <%= form.text_field :tipo %>
      </div>
      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
      </div>
      <div class="form-group">
        <%= form.label :apellidos %>
        <%= form.text_field :apellidos %>
      </div>

    </div>

    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <%= form.label :pais %>
        <%= form.text_field :pais %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      <div class="form-group">
        <%= form.label :contraseña %>
        <%= form.password_field :contraseña %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-2 mt-4">
    <%= form.submit "Guardar", class: "btn btn-dark" %>
    <%= link_to 'Cancelar', usuarios_index_path, class: "btn btn-primary ml-2" %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Editar usuario</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

          <div class="col-12">
            <%= render "usuarios/form" %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/usuarios/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">

    <div class="table-responsive">
      <div class="w-100 text-center">
        <h1>Usuarios</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <table class="table table-striped">
        <thead>
        <tr>
          <th class="text-center">Nombre</th>
          <th class="text-center">Apellidos</th>
          <th class="text-center">Pais</th>
          <th class="text-center">Correo</th>
          <th class="text-center" colspan="3">Acciones</th>
        </tr>
        </thead>

        <% @usuario.each do |usuario| %>
          <tbody>
          <tr>
            <td class="text-center align-middle"> <%= usuario.nombre %> </td>
            <td class="text-center align-middle"> <%= usuario.apellidos %> </td>
            <td class="text-center align-middle"> <%= usuario.pais %> </td>
            <td class="text-center align-middle"> <%= usuario.email %> </td>
            <td class="text-center align-middle">
              <%= link_to "Detalles", usuario, class: "btn btn-info " %>
              <%= link_to "Editar", edit_usuario_path(usuario.id), class: "btn btn-success ml-2" %>
              <%= link_to "Eliminar", usuario, method: :delete, class: "btn btn-danger ml-2",
                          data: { confirm: '¿Desea eliminar?'} %>
            </td>
          </tr>

          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</section>

app/views/usuarios/new.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="mb-2">Crear usuario</h1>
          <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">
          <div class="col-12">
            <%= render "usuarios/form" %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/usuarios/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <div class="w-100 text-center mb-3">
        <h1>Información del usuario</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <div class="row">
        <div class="col-md-12 text-center">
          <div>
            <p> Tipo: <%= @usuario.tipo %> </p>
          </div>

          <div>
            <p> Nombre: <%= @usuario.nombre %> </p>
          </div>

          <div>
            <p> Apellidos: <%= @usuario.apellidos %> </p>
          </div>

          <div>
            <p> Pais: <%= @usuario.pais %> </p>
          </div>

          <div>
            <p> Correo: <%= @usuario.email %> </p>
          </div>

          <div>
            <p> Contraseña: <%= @usuario.contraseña %> </p>
          </div>

          <div>
            <%= link_to "Editar", edit_usuario_path(@usuario.id), class: "btn btn-success" %>
            <%= link_to "Eliminar", @usuario, method: :delete, class: "btn btn-danger",
                        data: { confirm: '¿Desea eliminar?'} %>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>